#! /bin/bash
set -u
set -e
set -o pipefail
####################
# fq_count
#     Description:
#         Count the input fastq file records
#         Result will be outputted to stdout.
#     Usage:
#         fq_count [-h] -f input.fq
#     Parameters:
#         h: print this help
#         f: the fastq file of the single-end fastq files
#     Input:
#         the input file should be fastq files
#     Output:
#         record counts will be output to standard output /dev/stdout.
####################

function printusage {
    echo "Usage: $0 [-h] -f input.fq" 1>&2
}

function printhelp {
    printusage
    echo "" 1>&2
    echo "Parameters:" 1>&2
    echo "    h: print this help" 1>&2
    echo "    f: the fastq file to be count reads." 1>&2
    echo "" 1>&2
    echo "Input:" 1>&2
    echo "    the input file should be fastq files." 1>&2
    echo "" 1>&2
    echo "Output:" 1>&2
    echo "    the reads count will be output to /dev/stdout (1>)" 1>&2
}

ov=1

while getopts "hf:" opt; do
  case ${opt} in
    h)
      printhelp; exit 0
      ;;
    f)
      of=${OPTARG}
      ;;
    \?)
      echo "Invalid option: -"${OPTARG}
      printusage; exit 1
      ;;
  esac
done


# check the required parameters
if [ -z "${of}" ]; then
    printusage
    exit 1
fi

####################

file=${of}


awk 'BEGIN {
        reads=0;
    }
    FNR % 4 == 0 {
        reads += 1;
    }
    END {
        print reads;
    }' ${file}


####################
